// export const GET_PUBLICACIONES = 'traer_publicaciones'
export const ACTUALIZAR = 'traer_publicaciones_actualizadas'
export const CARGANDO = 'cargando_publicaciones'
export const ERROR = 'error_publicaciones'
export const COM_CARGANDO = 'cargando_publicaciones_comentarios'
export const COM_ERROR = 'error_publicaciones_comentarios'
export const COM_ACTUALIZAR = 'comentarios_actualizadar'